import { Asset } from "@/types";

export const MOCK_ASSETS: Asset[] = [
  {
    id: "1",
    title: "Lagos Street Market",
    description: "Vibrant street traders at Balogun Market, Lagos Island",
    region: "west-africa",
    country: "Nigeria",
    tags: ["market", "street", "Lagos", "trade", "people"],
    type: "photo",
    license: "standard",
    price: 1500,
    previewUrl: "https://images.unsplash.com/photo-1580746738099-f1b9b7a2c1e5?w=600&q=80",
    contributorId: "c1",
    contributorName: "Adaeze Okafor",
    width: 4000,
    height: 2667,
    createdAt: "2024-11-01",
    downloads: 142,
  },
  {
    id: "2",
    title: "Nairobi CBD Skyline",
    description: "Modern skyline of Nairobi's central business district at dusk",
    region: "east-africa",
    country: "Kenya",
    tags: ["city", "skyline", "Nairobi", "architecture", "dusk"],
    type: "photo",
    license: "standard",
    price: 1500,
    previewUrl: "https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=600&q=80",
    contributorId: "c2",
    contributorName: "Kamau Wanjiku",
    width: 5000,
    height: 3333,
    createdAt: "2024-10-15",
    downloads: 98,
  },
  {
    id: "3",
    title: "Kente Weaving, Accra",
    description: "Artisan weaving traditional Kente cloth in a workshop near Accra",
    region: "west-africa",
    country: "Ghana",
    tags: ["kente", "craft", "textile", "culture", "Ghana"],
    type: "photo",
    license: "standard",
    price: 2000,
    previewUrl: "https://images.unsplash.com/photo-1504805572947-34fad45aed93?w=600&q=80",
    contributorId: "c3",
    contributorName: "Ama Boateng",
    width: 3600,
    height: 2400,
    createdAt: "2024-09-20",
    downloads: 211,
  },
  {
    id: "4",
    title: "Cape Town Waterfront",
    description: "V&A Waterfront with Table Mountain backdrop at golden hour",
    region: "southern-africa",
    country: "South Africa",
    tags: ["Cape Town", "waterfront", "mountain", "sunset", "tourism"],
    type: "photo",
    license: "extended",
    price: 3500,
    previewUrl: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600&q=80",
    contributorId: "c4",
    contributorName: "Nomsa Dlamini",
    width: 6000,
    height: 4000,
    createdAt: "2024-12-01",
    downloads: 305,
  },
  {
    id: "5",
    title: "Cairo Old Quarter",
    description: "Narrow alleyways of Islamic Cairo with traditional architecture",
    region: "north-africa",
    country: "Egypt",
    tags: ["Cairo", "architecture", "Islamic", "heritage", "alley"],
    type: "photo",
    license: "standard",
    price: 1500,
    previewUrl: "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=600&q=80",
    contributorId: "c5",
    contributorName: "Fatima El-Sayed",
    width: 4200,
    height: 2800,
    createdAt: "2024-08-10",
    downloads: 176,
  },
  {
    id: "6",
    title: "Maasai Community Portrait",
    description: "Portrait of Maasai women in traditional dress, Rift Valley",
    region: "east-africa",
    country: "Tanzania",
    tags: ["Maasai", "portrait", "culture", "people", "traditional"],
    type: "photo",
    license: "editorial",
    price: 2500,
    previewUrl: "https://images.unsplash.com/photo-1521336575822-6da63fb45455?w=600&q=80",
    contributorId: "c6",
    contributorName: "Juma Rashidi",
    width: 3000,
    height: 4500,
    createdAt: "2024-07-22",
    downloads: 89,
  },
  {
    id: "7",
    title: "Dakar Fishing Village",
    description: "Colourful pirogues lined up on the beach in Yoff, Dakar",
    region: "west-africa",
    country: "Senegal",
    tags: ["fishing", "boats", "Dakar", "beach", "colourful"],
    type: "photo",
    license: "standard",
    price: 1500,
    previewUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80",
    contributorId: "c7",
    contributorName: "Ousmane Diallo",
    width: 4800,
    height: 3200,
    createdAt: "2024-11-30",
    downloads: 134,
  },
  {
    id: "8",
    title: "Johannesburg Tech Hub",
    description: "Young African entrepreneurs collaborating in a Sandton co-working space",
    region: "southern-africa",
    country: "South Africa",
    tags: ["tech", "business", "youth", "entrepreneur", "Johannesburg"],
    type: "photo",
    license: "standard",
    price: 2000,
    previewUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&q=80",
    contributorId: "c4",
    contributorName: "Nomsa Dlamini",
    width: 5200,
    height: 3467,
    createdAt: "2024-12-10",
    downloads: 67,
  },
];

export const REGIONS = [
  { value: "all", label: "All Regions" },
  { value: "west-africa", label: "West Africa" },
  { value: "east-africa", label: "East Africa" },
  { value: "southern-africa", label: "Southern Africa" },
  { value: "north-africa", label: "North Africa" },
  { value: "central-africa", label: "Central Africa" },
] as const;

export const ASSET_TYPES = [
  { value: "all", label: "All Types" },
  { value: "photo", label: "Photos" },
  { value: "vector", label: "Vectors" },
  { value: "video", label: "Video" },
] as const;
