import { Asset } from "@/types";

export const MOCK_ASSETS: Asset[] = [
  // ── AFRICA ──────────────────────────────────────────────
  {
    id: "1",
    title: "Lagos Street Market",
    description: "Vibrant street traders at Balogun Market, Lagos Island",
    region: "west-africa",
    country: "Nigeria",
    tags: ["market", "street", "Lagos", "trade", "people"],
    type: "photo",
    license: "standard",
    price: 0,
   previewUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    contributorId: "c1",
    contributorName: "Adaeze Okafor",
    width: 4000,
    height: 2667,
    createdAt: "2024-11-01",
    downloads: 142,
  },
  {
    id: "2",
    title: "Nairobi CBD Skyline",
    description: "Modern skyline of Nairobi's central business district at dusk",
    region: "east-africa",
    country: "Kenya",
    tags: ["city", "skyline", "Nairobi", "architecture", "dusk"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=600&q=80",
    contributorId: "c2",
    contributorName: "Kamau Wanjiku",
    width: 5000,
    height: 3333,
    createdAt: "2024-10-15",
    downloads: 98,
  },
  {
    id: "3",
    title: "Kente Weaving, Accra",
    description: "Artisan weaving traditional Kente cloth in a workshop near Accra",
    region: "west-africa",
    country: "Ghana",
    tags: ["kente", "craft", "textile", "culture", "Ghana"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1504805572947-34fad45aed93?w=600&q=80",
    contributorId: "c3",
    contributorName: "Ama Boateng",
    width: 3600,
    height: 2400,
    createdAt: "2024-09-20",
    downloads: 211,
  },
  {
    id: "4",
    title: "Cape Town Waterfront",
    description: "V&A Waterfront with Table Mountain backdrop at golden hour",
    region: "southern-africa",
    country: "South Africa",
    tags: ["Cape Town", "waterfront", "mountain", "sunset", "tourism"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600&q=80",
    contributorId: "c4",
    contributorName: "Nomsa Dlamini",
    width: 6000,
    height: 4000,
    createdAt: "2024-12-01",
    downloads: 305,
  },
  {
    id: "5",
    title: "Cairo Old Quarter",
    description: "Narrow alleyways of Islamic Cairo with traditional architecture",
    region: "north-africa",
    country: "Egypt",
    tags: ["Cairo", "architecture", "Islamic", "heritage", "alley"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=600&q=80",
    contributorId: "c5",
    contributorName: "Fatima El-Sayed",
    width: 4200,
    height: 2800,
    createdAt: "2024-08-10",
    downloads: 176,
  },
  {
    id: "6",
    title: "Maasai Community Portrait",
    description: "Portrait of Maasai women in traditional dress, Rift Valley",
    region: "east-africa",
    country: "Tanzania",
    tags: ["Maasai", "portrait", "culture", "people", "traditional"],
    type: "photo",
    license: "editorial",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1521336575822-6da63fb45455?w=600&q=80",
    contributorId: "c6",
    contributorName: "Juma Rashidi",
    width: 3000,
    height: 4500,
    createdAt: "2024-07-22",
    downloads: 89,
  },
  {
    id: "7",
    title: "Dakar Fishing Village",
    description: "Colourful pirogues lined up on the beach in Yoff, Dakar",
    region: "west-africa",
    country: "Senegal",
    tags: ["fishing", "boats", "Dakar", "beach", "colourful"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80",
    contributorId: "c7",
    contributorName: "Ousmane Diallo",
    width: 4800,
    height: 3200,
    createdAt: "2024-11-30",
    downloads: 134,
  },
  {
    id: "8",
    title: "Johannesburg Tech Hub",
    description: "Young African entrepreneurs collaborating in a Sandton co-working space",
    region: "southern-africa",
    country: "South Africa",
    tags: ["tech", "business", "youth", "entrepreneur", "Johannesburg"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&q=80",
    contributorId: "c4",
    contributorName: "Nomsa Dlamini",
    width: 5200,
    height: 3467,
    createdAt: "2024-12-10",
    downloads: 67,
  },
  {
    id: "9",
    title: "Moroccan Medina Spices",
    description: "Colourful spice stalls in the souks of Marrakech medina",
    region: "north-africa",
    country: "Morocco",
    tags: ["spices", "market", "Marrakech", "colour", "culture"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=600&q=80",
    contributorId: "c8",
    contributorName: "Youssef Benali",
    width: 4000,
    height: 2667,
    createdAt: "2024-10-05",
    downloads: 203,
  },
  {
    id: "10",
    title: "Serengeti Sunrise",
    description: "Golden sunrise over the vast Serengeti plains with acacia trees",
    region: "east-africa",
    country: "Tanzania",
    tags: ["safari", "sunrise", "Serengeti", "landscape", "nature"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=600&q=80",
    contributorId: "c6",
    contributorName: "Juma Rashidi",
    width: 5000,
    height: 3333,
    createdAt: "2024-09-01",
    downloads: 412,
  },
  {
    id: "11",
    title: "Accra Street Art",
    description: "Bold murals and street art decorating the walls of Accra",
    region: "west-africa",
    country: "Ghana",
    tags: ["art", "mural", "street", "Accra", "colour"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80",
    contributorId: "c3",
    contributorName: "Ama Boateng",
    width: 3800,
    height: 2533,
    createdAt: "2024-11-15",
    downloads: 88,
  },
  {
    id: "12",
    title: "Victoria Falls",
    description: "The mighty Victoria Falls at full flow on the Zambezi River",
    region: "southern-africa",
    country: "Zimbabwe",
    tags: ["waterfall", "nature", "Victoria Falls", "landscape", "water"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&q=80",
    contributorId: "c9",
    contributorName: "Tendai Moyo",
    width: 4500,
    height: 3000,
    createdAt: "2024-08-20",
    downloads: 267,
  },
  {
    id: "13",
    title: "Abuja Central Mosque",
    description: "The grand National Mosque of Nigeria at dusk in Abuja",
    region: "west-africa",
    country: "Nigeria",
    tags: ["mosque", "architecture", "Abuja", "religion", "Nigeria"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1585504198199-20277593b94f?w=600&q=80",
    contributorId: "c1",
    contributorName: "Adaeze Okafor",
    width: 4200,
    height: 2800,
    createdAt: "2024-07-10",
    downloads: 155,
  },
  {
    id: "14",
    title: "Ethiopian Coffee Ceremony",
    description: "Traditional Ethiopian coffee ceremony with incense and roasted beans",
    region: "east-africa",
    country: "Ethiopia",
    tags: ["coffee", "ceremony", "Ethiopia", "culture", "tradition"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    contributorId: "c10",
    contributorName: "Tigist Haile",
    width: 3600,
    height: 4800,
    createdAt: "2024-12-05",
    downloads: 193,
  },
  {
    id: "15",
    title: "Zanzibar Stone Town",
    description: "Historic coral stone buildings and narrow streets of Stone Town",
    region: "east-africa",
    country: "Tanzania",
    tags: ["Zanzibar", "architecture", "historic", "street", "heritage"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=600&q=80",
    contributorId: "c6",
    contributorName: "Juma Rashidi",
    width: 4000,
    height: 2667,
    createdAt: "2024-06-15",
    downloads: 144,
  },
  {
    id: "16",
    title: "Kigali Clean City",
    description: "Modern clean streets and green hills of Kigali, Rwanda",
    region: "central-africa",
    country: "Rwanda",
    tags: ["Kigali", "city", "modern", "Rwanda", "urban"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1612892483236-52d32a0e0ac1?w=600&q=80",
    contributorId: "c11",
    contributorName: "Amina Uwase",
    width: 5000,
    height: 3333,
    createdAt: "2024-11-20",
    downloads: 78,
  },

  // ── INDIA ──────────────────────────────────────────────
  {
    id: "i1",
    title: "Taj Mahal at Dawn",
    description: "The iconic Taj Mahal reflected in the pool at sunrise, Agra",
    region: "india" as any,
    country: "India",
    tags: ["Taj Mahal", "heritage", "Agra", "architecture", "sunrise"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    contributorId: "ci1",
    contributorName: "Priya Sharma",
    width: 5000,
    height: 3333,
    createdAt: "2024-11-10",
    downloads: 521,
  },
  {
    id: "i2",
    title: "Varanasi Ghats",
    description: "Morning prayers and rituals along the sacred ghats of Varanasi",
    region: "india" as any,
    country: "India",
    tags: ["Varanasi", "ghats", "religion", "Ganges", "ritual"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=600&q=80",
    contributorId: "ci2",
    contributorName: "Arjun Patel",
    width: 4000,
    height: 2667,
    createdAt: "2024-10-20",
    downloads: 344,
  },
  {
    id: "i3",
    title: "Rajasthan Desert Dunes",
    description: "Camel caravan crossing the golden sand dunes of Thar Desert",
    region: "india" as any,
    country: "India",
    tags: ["desert", "Rajasthan", "camel", "dunes", "landscape"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1518638150340-f706e86654de?w=600&q=80",
    contributorId: "ci1",
    contributorName: "Priya Sharma",
    width: 4800,
    height: 3200,
    createdAt: "2024-09-15",
    downloads: 289,
  },
  {
    id: "i4",
    title: "Mumbai Street Food",
    description: "Busy street food stalls serving vada pav in the heart of Mumbai",
    region: "india" as any,
    country: "India",
    tags: ["Mumbai", "street food", "market", "culture", "people"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&q=80",
    contributorId: "ci3",
    contributorName: "Deepa Nair",
    width: 3600,
    height: 2400,
    createdAt: "2024-12-01",
    downloads: 198,
  },
  {
    id: "i5",
    title: "Kerala Backwaters",
    description: "Traditional houseboat drifting through the tranquil Kerala backwaters",
    region: "india" as any,
    country: "India",
    tags: ["Kerala", "backwaters", "houseboat", "nature", "water"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    contributorId: "ci2",
    contributorName: "Arjun Patel",
    width: 5000,
    height: 3333,
    createdAt: "2024-08-25",
    downloads: 376,
  },
  {
    id: "i6",
    title: "Holi Festival Colours",
    description: "Joyful celebration of Holi with vibrant coloured powder in Jaipur",
    region: "india" as any,
    country: "India",
    tags: ["Holi", "festival", "colour", "celebration", "Jaipur"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1615308329878-b42194f9f7c0?w=600&q=80",
    contributorId: "ci3",
    contributorName: "Deepa Nair",
    width: 4200,
    height: 2800,
    createdAt: "2024-03-10",
    downloads: 612,
  },
  {
    id: "i7",
    title: "Jaipur Pink City",
    description: "The iconic pink-walled Hawa Mahal palace in the heart of Jaipur",
    region: "india" as any,
    country: "India",
    tags: ["Jaipur", "Hawa Mahal", "architecture", "pink", "heritage"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    contributorId: "ci1",
    contributorName: "Priya Sharma",
    width: 3800,
    height: 5000,
    createdAt: "2024-07-18",
    downloads: 445,
  },
  {
    id: "i8",
    title: "Tamil Nadu Temple",
    description: "Towering gopuram of a Dravidian temple in Tamil Nadu at dusk",
    region: "india" as any,
    country: "India",
    tags: ["temple", "Tamil Nadu", "architecture", "religion", "gopuram"],
    type: "photo",
    license: "standard",
    price: 0,
    previewUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&q=80",
    contributorId: "ci2",
    contributorName: "Arjun Patel",
    width: 4000,
    height: 6000,
    createdAt: "2024-06-30",
    downloads: 287,
  },
];

export const REGIONS = [
  { value: "all", label: "All Regions" },
  { value: "west-africa", label: "West Africa" },
  { value: "east-africa", label: "East Africa" },
  { value: "southern-africa", label: "Southern Africa" },
  { value: "north-africa", label: "North Africa" },
  { value: "central-africa", label: "Central Africa" },
  { value: "india", label: "India" },
] as const;

export const ASSET_TYPES = [
  { value: "all", label: "All Types" },
  { value: "photo", label: "Photos" },
  { value: "vector", label: "Vectors" },
  { value: "video", label: "Video" },
] as const;